[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@aqua/=lib/aqua/",
    "@swap-vm/=lib/swap-vm/",
    "@1inch/solidity-utils/=lib/aqua/node_modules/@1inch/solidity-utils/",
    "@openzeppelin/contracts/=lib/aqua/node_modules/@openzeppelin/contracts/",
    "forge-std/=lib/forge-std/src/",
]
auto_detect_remappings = false
via_ir = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
