[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@aqua/=lib/aqua/src/",
    "@swap-vm/=lib/swap-vm/src/",
    "@1inch/solidity-utils/=lib/aqua/lib/@1inch/solidity-utils/src/",
    "@openzeppelin/contracts/=lib/aqua/lib/@openzeppelin/contracts/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
